### ISSUE TITLE
Links to non-promoted networks don't work

### ISSUE THREAD

**Issue by alreadydone** [gcp/leela-zero-server#189]
When I tried to download 4dad2d0d (current best according to match results, albeit not promoted), I got a 404 Error. Suggestions: 
+ keep all networks that are still displayed on zero.sjeng.org
+ keep the best non-promoted network

**Comment by gcp** [comment]
They are all on http://storage.sjeng.org/networks/

The non-promoted networks take a huge amount of storage and are almost never used, so it makes no sense to keep them around on the main SSD. I move them to the storage server every now and then.

**Comment by alreadydone** [comment]
Would it be better then to point the network download links in pages like [this](http://zero.sjeng.org/network-profiles/fb01adbbe4ab0c5a8158ffd2aff3acc6bf15c20f0730bb45f472ba74b6e2204e) and on zero.sjeng.org to storage.sjeng.org instead?

**Comment by gcp** [comment]
No, because there's no guarantee the network is there yet. I could automate the rsync to run regularly, but if you click at a bad moment it would still fail. (And when the networks are still being tested, we definitely want people to fetch from the faster main server).

I don't immediately have a good solution for this.

**Comment by Mardak** [comment]
Is there a `.htaccess` with `RewriteEngine On`? If so, could probably just do something like (it's been a while since I used… so probably not right):
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_URI} ^/networks/
RewriteRule (.*) http://storage.sjeng.org/$1 [L,R=301]
```

Alternatively, perhaps server.js can either match .get("/networks/:hash") and check if the file exists, or potentially only do this in the .get("*") 404 catch-all and redirect conditionally instead of always 404.

**Comment by Mardak** [comment]
Oh nevermind about the server.js stuff. Looks like /networks/ is handled outside of express. (?)

**Comment by gcp** [comment]
We're using nginx but it might have similar rewrite rules.

/networks was handled outside node.js so that clients storming to download a network don't put load on node.js.

**Comment by Mardak** [comment]
Looks like there's `try_files` http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files

I've never configured nginx, but maybe something like:
```
location /networks/ {
  try_files $uri @storage;
}

location @storage {
  expires 30s;
  return 301 http://storage.sjeng.org$request_uri;
}
```

**Comment by gcp** [comment]
I'll try to fix this with a rewrite rule.

**Comment by gcp** [comment]
Deployed this, seems to work.
