### ISSUE TITLE
Promotions cause a server OOM & crash

### ISSUE THREAD

**Issue by gcp** [gcp/leela-zero-server#24]
The server crashed again the moment 545ca6d6 promoted.

SPRT: Early pass unshift: {"network1":"545ca6d6d67169785598ec0185a9210190631916234d11441f75c781194c7114","network2":"b3a80524d2c510ff135e9206b695cd4569ab21e9fb4b459d411e6d99d743b62e","network1_losses":176,"network1_wins":224,"game_count":400,"number_to_play":400,"options":{"resignation_percent":"10","randomcnt":"0","noise":"false","visits":"3200","playouts":"0"},"options_hash":"8e437d","_id":"5aa290ead673c13e086bea2d","requests":[{"timestamp":1520606259370,"seed":"15426959040761963065"},{"timestamp":1520606404067,"seed":"9746325423087964562"},{"timestamp":1520606571763,"seed":"16580710657720491257"},{"timestamp":1520606580447,"seed":"16803210646367956948"},{"timestamp":1520606730150,"seed":"11804692162579541323"},{"timestamp":1520606793332,"seed":"16792455889284891974"},{"timestamp":1520606800411,"seed":"17074950341021423086"},{"timestamp":1520606873443,"seed":"1363047869884431541"},{"timestamp":1520606912647,"seed":"13186829878514647212"},{"timestamp":1520606948105,"seed":"4876221839255503293"},{"timestamp":1520607209621,"seed":"13294983390378473327"},{"timestamp":1520607264205,"seed":"2072352293509791474"},{"timestamp":1520607324071,"seed":"7433034460698712929"},{"timestamp":1520607426391,"seed":"10925498146026071810"},{"timestamp":1520607453177,"seed":"11059906593898246272"},{"timestamp":1520607550908,"seed":"15738329820082264744"},{"timestamp":1520607641343,"seed":"17607041420013328261"},{"timestamp":1520607641804,"seed":"10299091724745074389"},{"timestamp":1520607647771,"seed":"3963822521222219833"},{"timestamp":1520607676241,"seed":"8280106471766603624"},{"timestamp":1520607746434,"seed":"17399650952629161304"},{"timestamp":1520607746768,"seed":"6321507196950574429"},{"timestamp":1520607751569,"seed":"11101163797199046942"},{"timestamp":1520607790973,"seed":"4916541775844161777"},{"timestamp":1520607798754,"seed":"18195082795667119871"},{"timestamp":1520607806399,"seed":"15415386411179661320"}],"game_color":false}
New best network copied from (fast check): /home/jroy/code/leela-zero-server/network/545ca6d6d67169785598ec0185a9210190631916234d11441f75c781194c7114.gz

....
<ton of these with no other messages>
ip_addr Sending index.html
ip_addr Sending index.html
ip_addr Sending index.html
[nodemon] app crashed - waiting for file changes before starting...

System logs indicate node used up all memory and got killed:

```
[8380894.117249] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
[8380894.117334] [15880]  1001 15880  1093307   457510    1681      78   337986             0 node
[8380894.117341] Out of memory: Kill process 15880 (node) score 656 or sacrifice child
[8380894.118034] Killed process 15880 (node) total-vm:4373228kB, anon-rss:1830040kB, file-rss:0kB
```
 
Nodemon did not want to restart the server as the source hadn't changed, so I "touched" it.

**Comment by gcp** [comment]
If I read that line correctly node was using 4.3G of memory.

**Comment by roy7** [comment]
Ok I'll experiment with this tonight.,

**Comment by roy7** [comment]
It's weird how so much ram can be used when the file uncompressed is only 37 meg.

**Comment by roy7** [comment]
I'm logging some various things now to try and isolate if it's too many requests for hashes and the LOCK isn't working or what's going on.

**Comment by marcocalignano** [comment]
Could this be a problem related to the MongoDB cache management?

**Comment by roy7** [comment]
Since it only happens at promotion I think it has to be node. Although mongo does use about 55% of system ram continually.

**Comment by gcp** [comment]
MongoDB is not involved at all in this.

**Comment by roy7** [comment]
Unless I'm confused the only thing promotion does is copy a file and calculate a new hash. And I have locks around the get best hash function. So it shouldn't do multiple re-calcs at once.

**Comment by roy7** [comment]
So basically, somehow, promotions will move virtual memory usage from 1.2 gig to 4.3 gig.

**Comment by roy7** [comment]
https://www.toptal.com/nodejs/debugging-memory-leaks-node-js-applications

Is a great resource from @Dorus.

**Comment by roy7** [comment]
Doing a bit of testing on my local server. Here's some basic memory stats when a network is updated and I call get_best_network_hash(). This is with a network file that is 13M gzip'ed. From [the docs](https://nodejs.org/api/process.html#process_process_memoryusage):

> heapTotal and heapUsed refer to V8's memory usage. external refers to the memory usage of C++ objects bound to JavaScript objects managed by V8. rss, Resident Set Size, is the amount of space occupied in the main memory device (that is a subset of the total allocated memory) for the process, which includes the heap, code segment and stack.
> 
> The heap is where objects, strings, and closures are stored. Variables are stored in the stack and the actual JavaScript code resides in the code segment.

LOCK requested get_best_network_hash
LOCK acquired get_best_network_hash
best-network.gz has changed
rss 117.25 MB
heapTotal 16.33 MB
heapUsed 12.81 MB
external 17.15 MB

File read.
rss 117.25 MB
heapTotal 16.33 MB
heapUsed 12.82 MB
external 29.63 MB

13M to read the file.

Buffer.from(data) complete.
rss 117.5 MB
heapTotal 16.33 MB
heapUsed 12.83 MB
external 42.12 MB

13M to build the buffer from the file.

Begin zlib.unzip
zlib.unzip loaded.
rss 152.64 MB
heapTotal 16.33 MB
heapUsed 13.21 MB
external 99.54 MB

35M rss + 57M external to unzip the file into a networkbuffer (rss may overlap external?)

End zlib.unzip
networkbuffer.toString() complete.
rss 187.96 MB
heapTotal 51.29 MB
heapUsed 48.11 MB
external 99.54 MB

35M rss + 35M heap to convert networkbuffer to a string (rss may overlap heap?)

checksum(network) complete.
rss 187.71 MB
heapTotal 51.29 MB
heapUsed 48.12 MB
external 99.54 MB

Calculating the hash not using any new ram of note.

Best case resident memory up by 60M to process the 13M file upload. Maybe as bad as 120M if we look at heapTotal + external instead of rss.

So a starting point as I learn to use pipes instead to see if it helps.

**Comment by roy7** [comment]
Testing streams:

LOCK requested get_best_network_hash
LOCK acquired get_best_network_hash
best-network.gz has changed
rss 79.54 MB
heapTotal 32.37 MB
heapUsed 13.25 MB
external 48.15 MB

Streams prepared.
rss 79.54 MB
heapTotal 32.37 MB
heapUsed 13.27 MB
external 48.17 MB

Streams completed.
rss 97.33 MB
heapTotal 32.37 MB
heapUsed 15.61 MB
external 95.66 MB

So either 47M if external is all that matters or 47M + 18M including rss.

**Comment by roy7** [comment]
Not sure why but some more testing is even better:

LOCK requested get_best_network_hash
LOCK acquired get_best_network_hash
best-network.gz has changed
rss 72.81 MB
heapTotal 16.33 MB
heapUsed 12.53 MB
external 17.17 MB

Streams prepared.
rss 72.81 MB
heapTotal 16.33 MB
heapUsed 12.56 MB
external 17.19 MB

Streams completed.
rss 73.7 MB
heapTotal 16.83 MB
heapUsed 13.1 MB
external 32.96 MB

**Comment by roy7** [comment]
With --trace-gc

LOCK requested get_best_network_hash
LOCK acquired get_best_network_hash
best-network.gz has changed
rss 72.15 MB
heapTotal 16.33 MB
heapUsed 12.44 MB
external 17.15 MB

Streams prepared.
rss 72.15 MB
heapTotal 16.33 MB
heapUsed 12.47 MB
external 17.18 MB

[9960:0x561007920ef0]    27647 ms: Mark-sweep 13.3 (17.8) -> 12.4 (17.8) MB, 2.3 / 0.0 ms  (+ 14.0 ms in 16 steps since start of marking, biggest step 1.2 ms, walltime since start of marking 17 ms) finalize incremental marking via task GC in old space requested
[9960:0x561007920ef0]    27752 ms: Mark-sweep 12.9 (17.8) -> 12.4 (17.8) MB, 0.9 / 0.0 ms  (+ 7.0 ms in 17 steps since start of marking, biggest step 0.7 ms, walltime since start of marking 8 ms) finalize incremental marking via task GC in old space requested
[9960:0x561007920ef0]    27985 ms: Scavenge 13.4 (17.8) -> 12.4 (17.8) MB, 0.8 / 0.0 ms  allocation failure
Streams completed.
rss 65.55 MB
heapTotal 16.33 MB
heapUsed 12.58 MB
external 20.07 MB

(allocation failure just means it was time to do GC, per google, not a true error to worry about)

**Comment by roy7** [comment]
https://github.com/gcp/leela-zero-server/commit/afdc4c1da2f6726b7f5c2405c7fc1ba34d7c1519

Current code. Before I move to live server, any feedback/advice/improvements?

There are other unzips in server.js I'll want to port over too. In testing locally this works and gives me the correct hash.

**Comment by roy7** [comment]
Perhaps the amount of ram used varies based on speed of each stage of the pipeline. The slowest stage would be the gzip. I didn't try testing this on actual server, but I imagine it's impossible to be worse than current code on server. ;)

**Comment by roy7** [comment]
https://nodejs.org/en/docs/guides/backpressuring-in-streams/

**Comment by roy7** [comment]
I'd like to capture one more promotion/memory problem with all of the logging in place before deploying the pipe/stream change. That'll help confirm this truly was the problem area of the code. But LZ isn't cooperating. :) f4c37ceb came close though, was 4 wins away when it hit 400 games total. I was tempted to force promote it just to stress the server lol.

**Comment by roy7** [comment]
I could force a "promotion" event in the server by touching best-network.gz. No actual new hash/network to affect database, and clients won't download it since hash hasn't changed, but I could see what happens with server ram usage... I guess I'll try that now while I'm here to observe and restart node if server gets into trouble.

**Comment by roy7** [comment]
Hmm caused no problem at all. Grr. 

LOCK requested get_best_network_hash
LOCK acquired get_best_network_hash
best-network.gz has changed
rss 99.71 MB
heapTotal 39.47 MB
heapUsed 29.12 MB
external 18.14 MB
File read.
rss 99.71 MB
heapTotal 39.47 MB
heapUsed 29.13 MB
external 30.32 MB
Buffer.from(data) complete.
rss 99.71 MB
heapTotal 39.47 MB
heapUsed 29.14 MB
external 42.5 MB
Begin zlib.unzip
XXX uploaded game #5201440: 5651b1d7e745fbe894ae0a691f1ff7ca939e6c9b33aa3f260f0e8c82e36f21d6
XXX Sending index.html
LOCK requested get_best_network_hash
LOCK acquired get_best_network_hash
best-network.gz has changed
rss 104.32 MB
heapTotal 44.62 MB
heapUsed 22.11 MB
external 65.9 MB
zlib.unzip loaded.
rss 151.5 MB
heapTotal 44.62 MB
heapUsed 22.22 MB
external 113.58 MB
End zlib.unzip
networkbuffer.toString() complete.
rss 186.57 MB
heapTotal 79.58 MB
heapUsed 57.18 MB
external 113.58 MB
checksum(network) complete.
rss 186.59 MB
heapTotal 79.58 MB
heapUsed 57.19 MB
external 113.58 MB
File read.
rss 151.06 MB
heapTotal 44.12 MB
heapUsed 22.14 MB
external 111.5 MB
Buffer.from(data) complete.
rss 151.06 MB
heapTotal 44.12 MB
heapUsed 22.15 MB
external 123.69 MB
Begin zlib.unzip
LOCK requested get_best_network_hash
LOCK acquired get_best_network_hash
XXX got task: selfplay
XXX uploaded game #5201441: 17b504a680e72c5d30cd117cb35bdc8d6af5513af040f0b0100b24f1a8892cb4
LOCK requested get_best_network_hash
LOCK acquired get_best_network_hash
XXX got task: selfplay
XXX  uploaded game #5201442: 68c81622b184b5e22963fe4574e707a7766e90b843ffb9a1c121f20452cc84e5
XXX Sending index.html
LOCK requested get_best_network_hash
LOCK acquired get_best_network_hash
zlib.unzip loaded.
rss 150.88 MB
heapTotal 44.12 MB
heapUsed 22.42 MB
external 99.39 MB
End zlib.unzip
networkbuffer.toString() complete.
rss 185.95 MB
heapTotal 79.08 MB
heapUsed 57.38 MB
external 99.39 MB
checksum(network) complete.
rss 186.07 MB
heapTotal 79.08 MB
heapUsed 57.39 MB
external 99.39 MB

I do see, however, the LOCK didn't work. A second person got the lock after the first person acquired it.

So if we do a promotion and get lots of people all starting the zip process at once, then maybe that's why the RAM usage gets out of control to sink server. (And each unzip running at once bogs down cpu making it worse.)

**Comment by roy7** [comment]
I'm asking about the lock here:

https://github.com/rogierschouten/async-lock/issues/13

**Comment by roy7** [comment]
Using streams/pipe instead of storing everything in ram: https://github.com/gcp/leela-zero-server/commit/afdc4c1da2f6726b7f5c2405c7fc1ba34d7c1519

Storing a promise to return to avoid simultaneous unzip: https://github.com/gcp/leela-zero-server/commit/c200946934a361587d474ba0a4c15516f1eac6e6

**Comment by roy7** [comment]
Much much thanks to @Dorus.

**Comment by roy7** [comment]
New code uses way less ram, and the file will only be unzip'ed one time to calculate the new hash. All clients who need a new hash in the mean time will wait patiently with no external lock module/etc.

If the day comes a network file is too large to unzip/hash using streams/pipe then the server needs more memory. :)

**Comment by gcp** [comment]
>Storing a promise to return to avoid simultaneous unzip: c200946

Could this have been the underlying issue?

**Comment by gcp** [comment]
Thanks for investigating this. I was considering getting a larger VPS to avoid us getting blocked from trying larger networks, but this bug made me concerned it didn't matter how big I machine I'd get...

**Comment by roy7** [comment]
I'm not sure if it was the unzips or the ram per se. Once too much ram is used and server starts thrashing, it might enter a death spiral. But if too many unzips start at once, more and more would keep piling up until the first one finished and had a cache figure to tell new requests. But by then if there are dozens running, cpu would be in serious trouble.

Since we've seen node die from too much ram allocation, what must have happened is the unzips slowed down as more and more backed up, the ram usage just got out of control as each unzip was using way too much memory, and the combination killed things.

Now, we only do 1 unzip at a time per promotion, and it only uses portion of the ram it used to. In theory, even if we we were on much larger networks, promotions should never crash us again.

Silver lining, I learned a lot more about promises.
