### ISSUE TITLE
Discussion: SPRT early fail/pass result affected by late matches received.

### ISSUE THREAD

**Issue by rchs819** [gcp/leela-zero-server#55]
The network `02e663b0` had a SPRT early fail around 39x games.

The late matches received have pushed the result to a `pass`, it didn't get promoted (as expected).

![image](https://user-images.githubusercontent.com/35659961/38530518-54e24d06-3cae-11e8-9eff-30a043d4110e.png)

However, leaving the SPRT showing `pass` (in fact an early fail) would  confuse the crowd.

I would suggest to store SPRT early pass/fail result in database, so that the late matches received wouldn't affect the SPRT result.

Any thoughts?

Edit:
@roy manually promoted `02e663b0`, further late matches received have push the result back to `fail`

**Comment by alreadydone** [comment]
I think it is automatically promoted, not manually. It's possible for a failed network to pass as more games come in, but not possible to un-promote a passed network, so it has been implemented that a network won't be promoted before 100 games (IIRC), but after 100 games it can very well be promoted but later fails.

**Comment by rchs819** [comment]
If it was auto promoted, the next match should play against the new network.

@roy7 
I might have mistaken your https://github.com/gcp/leela-zero/issues/1180#issuecomment-379943059
Could you clarify if you did any manual promotions, or we might have a race condition here.

**Comment by roy7** [comment]
Nothing was manually promoted. However, promotion is only if you pass vs current best network. So what can happen is:

X is best network.
A barely fails by hitting 400 max limit.
B starts vs X.
A has more games arrive and becomes a pass vs X, A becomes new best network.
B passes vs X but X isn't best network any more, so nothing happens.

This only happens in cases where B starts because A is "done" but then A passes because of more matches that stroll in after the fact.

**Comment by rchs819** [comment]
Thanks for clarification.
